/**
 * GitHub Immutable Contribution Credential v2 — machine-readable contract (canonical).
 *
 * A credential proves a GitHub FACT (a merged PR) observed via a GitHub API response. It is a *candidate* for RFC-017's contribution fact layer — NOT a
 * Passkey/KYC claim, scoring, or reward. Distinct from: Contribution Fact (RFC-017
 * authoritative, produced later), Identity Claim (future Passkey), Valuation/Reward (never here).
 *
 * Immutability model (Codex #294 audit):
 *   - `core`  = the immutable GitHub fact. `core_digest` (and `credential_id` derived from it)
 *               authenticate ONLY this. Lifecycle parent link `supersedes_credential_id` is in core.
 *   - `observation` = a NON-authoritative, MUTABLE envelope (display names, observed_at,
 *               self-reported task/provenance, evidence summaries). It carries its OWN
 *               `observation_digest`. The same fact re-observed → same credential_id/core_digest,
 *               possibly different observation_digest. credential_id does NOT authenticate the
 *               observation envelope.
 *
 * Trust boundary: this is a PURE verifier over a CALLER-SUPPLIED response. It validates
 * STRUCTURE + repository anchoring; it does NOT prove the response authentically came from
 * GitHub. `verification_state='verified'` = structural + repo-anchor verification only.
 * Source-authenticity (authenticated fetch) is deferred to PR 3B.
 *
 * Canonical = zod (no new dependency). The committed JSON Schema is generated by
 * `toJSONSchema()` (drift-guarded) and carries the cross-field rules as `allOf` if/then.
 */
import { z } from 'zod'

export const CONTRIBUTION_TYPES = ['code', 'tests', 'audit', 'maintenance', 'governance', 'usage', 'transaction', 'referral'] as const   // RFC-017 §5
// 'unknown' included so a missing/invalid self-report is recorded honestly, NOT guessed as human.
export const PROVENANCE = ['human', 'ai_assisted', 'ai_authored', 'unknown'] as const
// 'unknown' included so a missing GitHub visibility is recorded honestly, NOT assumed public.
export const VISIBILITY = ['public', 'private', 'internal', 'unknown'] as const
export const VERIFICATION_STATE = ['verified', 'unverified', 'insufficient_evidence'] as const
export const EVIDENCE_SCOPE = ['public_metadata', 'repo_collaborator_metadata'] as const
export const DCO_STATE = ['present', 'absent', 'unknown'] as const
// per-evidence-stream coverage — machine-readable so a consumer can tell "observed zero" from
// "not observed". 'partial' = fetched but truncated at the page cap (more may exist).
export const EVIDENCE_COVERAGE = ['observed', 'unobserved', 'partial'] as const
// The PURE PR verifier mints ONLY the `merged` lifecycle (merged-only profile). A pure PR response
// cannot independently prove reverted / superseded / void (it only proves THIS PR merged, not that
// it rolled back a target credential) — ALL of them are DEFERRED to a separate lifecycle-event
// verifier (PR 3B) with their own trusted evidence + reason rules. The field/enum keeps the slot
// for forward compatibility; the verifier forces `merged` + `supersedes_credential_id = null`.
export const LIFECYCLE_EVENT = ['merged'] as const

const SHA256_HEX = /^[0-9a-f]{64}$/
const nonNegInt = z.number().int().min(0)

export const CREDENTIAL_TYPE = 'github_contribution_credential' as const
// v2 (PR 3B-2): adds observation.evidence_coverage. A strict schema rejects unknown fields in BOTH
// directions, so an additive field is NOT v1-compatible — this is a formal version bump. There are
// no persisted v1 credentials (no storage yet), so v2 cleanly supersedes. credential_version is in
// the digest, so v2 of the same GitHub fact gets a different credential_id (domain/version isolation).
export const CREDENTIAL_VERSION = '2' as const

// ── immutable GitHub fact core ──────────────────────────────────────────────
// strictObject: reject unknown fields so the immutable core cannot carry un-digested claims,
// and so zod matches the JSON Schema's additionalProperties:false (consumer parity).
export const CoreObject = z.strictObject({
  credential_type: z.literal(CREDENTIAL_TYPE),       // fixed protocol domain (digest isolation)
  credential_version: z.literal(CREDENTIAL_VERSION), // version domain (v2 of same fact ⇒ different id)
  repository_id: z.string().min(1),                  // stable GitHub node/database id
  pr_node_id: z.string().min(1),                     // stable
  pr_number: z.number().int().positive(),
  base_ref: z.string().min(1),
  head_sha: z.string().min(1),                       // actual observed head sha (force-push aware)
  merge_commit_sha: z.string().min(1).nullable(),
  merged_at: z.string().min(1).nullable(),
  github_actor_id: z.string().min(1),                // stable
  lifecycle_event: z.enum(LIFECYCLE_EVENT),
  supersedes_credential_id: z.string().min(1).nullable(),   // merged-only profile ⇒ always null (reverted/etc. deferred)
})

// ── non-authoritative, mutable observation envelope (strictObject — reject unknown fields) ──
export const ObservationObject = z.strictObject({
  observed_at: z.string().min(1),
  repository_owner: z.string().min(1),               // display (mutable)
  repository_name: z.string().min(1),                // display (mutable)
  repository_visibility_at_observation: z.enum(VISIBILITY),   // 'unknown' when GitHub didn't say (never guessed public)
  head_ref: z.string().min(1),                       // display (branch may be renamed/deleted)
  github_login: z.string().min(1),                   // display (mutable)
  commit_authors: z.array(z.strictObject({
    author_id: z.string().nullable(), login: z.string().nullable(), name: z.string().nullable(), is_coauthor: z.boolean(),
  })),                                               // NO emails (rule 10)
  agent_provenance: z.enum(PROVENANCE),              // self-declared; 'unknown' when not validly self-reported (never guessed human)
  claimed_task_id: z.string().nullable(),            // self-reported, NON-authoritative (rule 1/9)
  source_ref: z.string().nullable(),                 // self-reported, NON-authoritative
  contribution_type: z.enum(CONTRIBUTION_TYPES).nullable(),   // candidate classification; null when not self-reported (never guessed 'code')
  verification_state: z.enum(VERIFICATION_STATE),    // structural + repo-anchor only (see trust boundary)
  evidence_scope: z.enum(EVIDENCE_SCOPE),
  checks_summary: z.strictObject({ total: nonNegInt, success: nonNegInt, failure: nonNegInt, neutral: nonNegInt, other: nonNegInt }),
  reviews_summary: z.strictObject({ approved: nonNegInt, changes_requested: nonNegInt, commented: nonNegInt, reviewer_ids: z.array(z.string()) }),
  dco_state: z.enum(DCO_STATE),                      // independent of co-authors (rule 8)
  // machine-readable per-stream coverage: distinguishes "observed zero" from "not observed".
  // A summary's zeros/unknown are only meaningful when its coverage is 'observed'.
  // required in v2 — every minted credential reports per-stream coverage.
  evidence_coverage: z.strictObject({
    checks: z.enum(EVIDENCE_COVERAGE),
    reviews: z.enum(EVIDENCE_COVERAGE),
    commit_authors: z.enum(EVIDENCE_COVERAGE),
    dco: z.enum(['observed', 'unobserved']),         // single check, no pagination → no 'partial'
  }),
  merged_by_actor_id: z.string().nullable(),
  evidence_refs: z.array(z.string()),               // stable refs (no tokens/PII)
  known_limitations: z.array(z.string()),
})

export const GithubCredentialObject = z.strictObject({
  credential_id: z.string().min(1),                  // = ghc_<core_digest[0:40]>; authenticates ONLY core
  event_source: z.literal('github_api'),             // CLAIMED source; not proof of source authenticity (see trust boundary)
  accountable_party_ref: z.null(),                   // rule 7: reserved, set later on the FACT (not here)
  core: CoreObject,
  core_digest: z.string().regex(SHA256_HEX),         // SHA-256 over core fields — the immutable fact identity
  observation: ObservationObject,
  observation_digest: z.string().regex(SHA256_HEX),  // SHA-256 over the observation envelope (a specific observation)
})

export const GithubCredentialSchema = GithubCredentialObject.superRefine((c, ctx) => {
  // merged-only profile: lifecycle is `merged` only ⇒ a merge happened, verified, and NO parent link.
  if (c.core.lifecycle_event === 'merged') {
    if (c.core.merge_commit_sha === null) ctx.addIssue({ code: 'custom', path: ['core', 'merge_commit_sha'], message: 'merged requires merge_commit_sha' })
    if (c.core.merged_at === null) ctx.addIssue({ code: 'custom', path: ['core', 'merged_at'], message: 'merged requires merged_at' })
    if (c.observation.verification_state !== 'verified') ctx.addIssue({ code: 'custom', path: ['observation', 'verification_state'], message: 'minted credential requires verification_state=verified' })
    if (c.core.supersedes_credential_id !== null) ctx.addIssue({ code: 'custom', path: ['core', 'supersedes_credential_id'], message: 'merged must NOT supersede (null parent link)' })
  }
})

export type GithubContributionCredential = z.infer<typeof GithubCredentialObject>

/** Structural JSON Schema (Draft 2020-12) + cross-field if/then (parity with superRefine). */
export function toJSONSchema(): Record<string, unknown> {
  const base = z.toJSONSchema(GithubCredentialObject) as Record<string, unknown>
  base.allOf = [
    // merged ⇒ merge anchors present + verified + NO parent link
    {
      if: { properties: { core: { properties: { lifecycle_event: { const: 'merged' } }, required: ['lifecycle_event'] } }, required: ['core'] },
      then: {
        properties: {
          core: { properties: { merge_commit_sha: { type: 'string' }, merged_at: { type: 'string' }, supersedes_credential_id: { type: 'null' } }, required: ['merge_commit_sha', 'merged_at', 'supersedes_credential_id'] },
          observation: { properties: { verification_state: { const: 'verified' } }, required: ['verification_state'] },
        },
        required: ['core', 'observation'],
      },
    },
  ]
  return base
}
