/**
 * RFC-011 §④ 契约变更体系 —— 让 feed 诚实(防 CHANGELOG-rot 那个失败模式)。
 *
 * 思路:给每个【契约面】(②能力矩阵 / ①实体字典)算确定性指纹(canonical + sha256),
 *   排除 software_version 等易变位 —— 只盖集成方依赖的契约内容。committed 基线 docs/CONTRACT-LOCK.json
 *   按 contract_version 锁;tests/test-contract-fingerprint.ts 守卫:指纹变了但 CONTRACT_VERSION 没 bump
 *   → FAIL,逼"bump + 写 CONTRACT_CHANGES 条目 + 更基线"。静默改契约不可 merge(= schema:verify 模式)。
 *
 * 版本模型:CONTRACT_VERSION = 契约内容修订号,任何 integrator-observable 变更都 bump;
 *   变更条目的 kind(added|changed|deprecated|removed)由人分类是否破坏性(additive agent 可忽略)。
 */
import { createHash } from 'node:crypto'
import { capabilityMatrix } from './endpoint-actions.js'
import { buildEntityDictionary } from './entity-dictionary.js'
import { canonicalSerialize } from '../layer0-foundation/L0-2-state-machine/order-chain.js'
import { CONTRACT_VERSION } from '../version.js'

const sha256 = (s: string) => createHash('sha256').update(s).digest('hex')

// 契约投影 —— 只取集成方依赖的契约内容,【排除】software_version / 易变 roadmap(todo)。
function contractProjection() {
  const cap = capabilityMatrix()
  const ent = buildEntityDictionary()
  return {
    capability: { model: cap.model, write_actions: cap.write_actions, safe_write_unscoped: cap.safe_write_unscoped, read_scopes: cap.read_scopes, notes: cap.notes },
    entity: { note: ent.note, entities: ent.entities },   // 注:不含 ent.software_version / ent.todo
  }
}

export function contractFingerprints(): { contract_version: number; capability: string; entity: string; combined: string } {
  const p = contractProjection()
  const capability = sha256(canonicalSerialize(p.capability))
  const entity = sha256(canonicalSerialize(p.entity))
  return { contract_version: CONTRACT_VERSION, capability, entity, combined: sha256(`${capability}|${entity}`) }
}

// 契约变更注册表(authored)—— 每个 integrator-observable 变更一条;agent 按 since 取比它新的。
export interface ContractChange { contract_version: number; date: string; surface: 'capability' | 'entity' | 'versioning' | 'eventing' | 'integration' | 'all'; kind: 'genesis' | 'added' | 'changed' | 'deprecated' | 'removed'; summary: string; migration?: string }
export const CONTRACT_CHANGES: ContractChange[] = [
  { contract_version: 1, date: '2026-06-06', surface: 'all', kind: 'genesis', summary: 'Contract v1 baseline: capability matrix (§②), entity dictionary + order lifecycle (§①), event cursor stream (§⑥), two version axes (§④).' },
  { contract_version: 2, date: '2026-06-06', surface: 'entity', kind: 'added', summary: '§① entity dictionary gains product + dispute entities (conservative public fields; dispute = redacted dispute_cases) + goal_index pointer. Additive — existing order entity unchanged; agents may ignore.' },
  { contract_version: 3, date: '2026-06-09', surface: 'entity', kind: 'changed', summary: '§① order lifecycle: corrected declined_nofault state meaning text — it is NOT terminal (transitions declined_nofault→completed on settlement). Dropped the contradictory "(terminal)" label that conflicted with the auto-derived terminal:false. Semantics/state-machine unchanged; text-only clarification for agents reading the entity dictionary.' },
  { contract_version: 4, date: '2026-06-09', surface: 'capability', kind: 'changed', summary: '§② capability matrix: POST /api/reviews/:type/:id/claim now requires the new "review_claim" action scope instead of being SAFE (unscoped). The review-claim path locks a 5 WAZ stake (escrow), so it belongs under default-deny accountability like other value writes. GET reviews endpoints stay open.', migration: 'A declared agent that calls review claim must add the "review_claim" scope to its api_key (or hold a Passkey, or declare "*"). Passkey-bound humans and "*" agents are unaffected; GET reviews unchanged.' },
  { contract_version: 5, date: '2026-06-24', surface: 'integration', kind: 'added', summary: '§④ integration-contract entry (/.well-known/webaz-integration.json) gains an agent_quickstart block: a 60-second stranger-agent cold-start with discrete, machine-parseable fields (canonical_start_url, public_readonly_entrypoints, anonymous_allowed_actions, authenticated_required_actions, safe_next_actions, proposal_flow, contribution_boundary). Additive — no existing field changed; agents may ignore. NB: this surface is NOT covered by the §②/§① fingerprint, so it is registered here by hand.' },
  { contract_version: 6, date: '2026-06-27', surface: 'entity', kind: 'added', summary: '§① order lifecycle gains two Direct Pay Rail 1 (non-custodial off-protocol payment) states: direct_pay_window (seller fee-stake locked, payment method shown, awaiting buyer off-protocol payment) and direct_expired_unconfirmed (payment window timed out without buyer confirmation — order is NOT silently closed; buyer retains a dispute/confirm window). Additive — existing order states/transitions unchanged; escrow orders never enter these states; agents may ignore unless they place direct_p2p orders.' },
  { contract_version: 7, date: '2026-06-27', surface: 'capability', kind: 'added', summary: '§② capability matrix RESERVES a new "direct_pay" action scope for the future /api/direct-pay/* surface (Direct Pay Rail 1). SCAFFOLD ONLY: this revision ships the D1/D2 disclosure helper + append-only ack model and a Passkey RISK-guard helper for later wiring — NO production route is gated yet, and the current order-action paths (mark_paid / cancel / confirm / confirm-in-person) do NOT yet enforce the Passkey or the two-disclosure-ack gate. The classifier maps /api/direct-pay/* → direct_pay so that surface is RISK-scoped the moment routes are added. Additive — no existing action changed.', migration: 'No behavioural change yet — do NOT assume Direct Pay order actions are Passkey-gated or disclosure-gated at this revision, and do NOT assume agents are blocked from them. Real enforcement (Passkey + two-disclosure-ack on mark_paid/confirm/confirm-in-person) is wired in a later PR together with the create route, ack endpoints, and UI.' },
  { contract_version: 8, date: '2026-07-02', surface: 'capability', kind: 'added', summary: 'Direct Pay Rail 1 (non-custodial) buyer account selection: POST /api/orders now accepts an OPTIONAL direct_receive_account_id — when a seller offers multiple receive accounts (GET /api/direct-receive/selectable-accounts, metadata-only), the buyer picks one and the create route snapshots THAT account. Omitted → unchanged dual-read fallback to the seller\'s single legacy payment instruction (no behaviour change for sellers with only that). The direct_p2p order gains a direct_pay_account_snapshot (non-sensitive metadata {account_id,method,currency,label,qr_ref} frozen at create); the raw instruction text stays in the existing disclosure-gated snapshot. New buyer read GET /api/orders/:id/direct-pay-qr serves the snapshotted receive-QR image bytes, gated to the order buyer AND both D1/D2 disclosure acks (non-enumerating 404 otherwise). Additive — this create-body field + order-metadata snapshot are NOT part of the §②/§① fingerprint projection, so registered here by hand; no existing action or order state changed.', migration: 'Agents placing direct_p2p orders MAY pass direct_receive_account_id (from selectable-accounts) to choose how they pay; omitting it preserves the prior single-instruction behaviour. The raw payment instruction and the QR image remain revealed only after both disclosure acks.' },
  { contract_version: 9, date: '2026-07-03', surface: 'entity', kind: 'added', summary: '§① order lifecycle gains a Direct Pay Rail 1 (non-custodial) negotiation state payment_query + its transitions (accepted→payment_query, payment_query→{accepted,cancelled,disputed}, disputed→payment_query withdraw). NOW LIVE & ENFORCED (staged PR-A state-machine → PR-B routes + timing → PR-C UI, all shipped on this same v9 surface — the wiring needed no dictionary change): for direct_p2p, seller non-receipt → payment_query = bilateral negotiation (争议) that PRECEDES 举证仲裁, not arbitration-on-first-report. The legacy accepted→disputed "未收到货款" button is RETIRED for direct_p2p (seller now uses report_nonpayment → payment_query). Flow: payment_query→disputed = evidence-required escalation (举证仲裁); confirm-received resume (payment_query→accepted); buyer/seller cancel; a 7-day buyer-recourse window after seller request-cancel; withdraw-before-ruling (disputed→payment_query) — RESTRICTED (route + DTO fail-closed) to disputes that were themselves escalated from payment_query, so fulfilment disputes (delivered→disputed, 货损/货不对版) are NOT withdrawable. Additive — existing states/transitions unchanged; escrow never uses these transitions (route guard enforces direct_p2p-only entry).', migration: 'direct_p2p non-receipt now uses the payment_query negotiation stage — seller 未收到货款 opens bilateral negotiation, NOT immediate arbitration. Legacy accepted→disputed is retired for direct_p2p (escrow-rail disputes unchanged). Agents/integrators: treat payment_query as a live order state; disputed→payment_query withdraw is available only for payment_query-escalated disputes (server returns NOT_PAYMENT_QUERY_DISPUTE otherwise) and can_withdraw_payment_query_dispute on the order DTO signals when it is offered.' },
  { contract_version: 10, date: '2026-07-03', surface: 'capability', kind: 'added', summary: 'Mutual cancel (协商取消): a no-fault, both-parties-consent way to terminate a DISPUTED order, alongside arbitration. New party-only endpoints POST /api/orders/:id/mutual-cancel/{propose,accept,decline,withdraw} + GET /api/orders/:id/mutual-cancel (current proposal + the caller\'s available actions). Handshake: either party (buyer/seller) proposes; the counterparty accepts → executed atomically (db.transaction). Outcome is NEUTRAL: the order goes to the existing terminal state \'cancelled\' (no new state or transition edge — reuses disputed→cancelled, executed by the protocol on consent), the active dispute is resolved in the SAME tx (verdict=mutual_cancel) so timeout auto-judge cannot double-settle, the buyer is made whole (escrow-rail → full escrow refund + seller stake returned; direct_p2p → zero funds, protocol never held them), and NEITHER party takes any reputation/fault/fee (no dispute_loss_count, no arbitration fee). Because it adds neither an order state/edge (§①) nor a named capability scope (§②), the §②/§① fingerprint is UNCHANGED — registered here by hand. Enforcement: these writes carry NO per-action Passkey / human-presence gate (unlike withdraw / arbitrate / direct-pay actions) — the safeguard is the two-party consent handshake itself (a single compromised session cannot unilaterally cancel, because the counterparty must independently accept). They classify under the generic default-deny \'write\' scope: session-authenticated parties and \'*\' agents may call them; narrow-scope declared agents are default-denied (an order-unwinding money action is not a delegated narrow scope).', migration: 'Agents/integrators: a disputed order can now reach \'cancelled\' via bilateral mutual-cancel consent (not only via arbitration ruling or timeout). Poll GET /api/orders/:id/mutual-cancel for a pending proposal and the caller\'s can_{propose,accept,decline,withdraw} flags. No existing action, order state, or transition changed. Escrow refund on accept touches ONLY funds actually locked for the order: buyer made-whole is FAIL-CLOSED — the buyer\'s real escrowed must be ≥ the order total or the accept aborts with ESCROW_INSUFFICIENT (no partial refund, no close, dispute stays open); seller stake return is best-effort from the order snapshot stake_backing+bid_stake_held (capped to real staked, never the product\'s nominal stake_amount). GET .../mutual-cancel is party-gated (non-party → 403; no proposal/reason leak).' },
  { contract_version: 11, date: '2026-07-03', surface: 'entity', kind: 'added', summary: '§① order lifecycle: the disputed→payment_query edge gains \'system\' as an allowed actor (was buyer/seller only). This backs a new arbitrator action "dismiss arbitration → back to negotiation" (ruling=dismiss_to_negotiation on POST /api/disputes/:id/arbitrate): an arbitrator may decline to rule winner/loser and instead return a Direct Pay (direct_p2p) payment-query-originated dispute to bilateral negotiation. It is NOT a merit ruling — no refund/liability/settlement, no arbitration fee, no reputation change, no escrow movement. Effect mirrors the party pq_withdraw close: order disputed→payment_query (executed by sys_protocol under the arbitrator\'s live-Passkey authorization + active-whitelist + COI/assignment gates), active dispute→dismissed (ruling_type=dismiss_to_negotiation), payment_query_deadline rebuilt, payment_query_cancel_deadline cleared, both parties notified. RESTRICTED (route + domain fail-closed) to direct_p2p disputes whose most recent entry into disputed was from payment_query — fulfilment disputes (delivered→disputed) and escrow disputes are rejected (NOT_PAYMENT_QUERY_DISPUTE / ARBITRATION_DISMISS_NOT_ALLOWED), so escrow funds are never touched. Additive — no state added, no existing edge/actor removed; the §① entity fingerprint changes only because allowed_roles on this one edge grew.', migration: 'Agents/integrators arbitrating direct_p2p payment-query disputes now have a fifth ruling option dismiss_to_negotiation that returns the order to payment_query instead of ruling. The order DTO / dispute detail expose can_dismiss_to_negotiation to signal when it is offered. Server returns NOT_PAYMENT_QUERY_DISPUTE / ARBITRATION_DISMISS_NOT_ALLOWED for fulfilment/escrow disputes. Like all arbitrate rulings it requires a purpose=\'arbitrate\' WebAuthn gate token bound to the dispute_id.' },
  { contract_version: 12, date: '2026-07-04', surface: 'entity', kind: 'added', summary: '§① order lifecycle gains an accepted→cancelled edge, allowed actor \'system\' ONLY. This backs the Direct Pay Rail 1 (non-custodial) post-payment cancel-refund handshake: after the buyer has paid off-protocol (mark_paid → accepted) and BEFORE the seller ships, the buyer may request cancellation. Because the protocol never held the buyer\'s money it cannot refund — the refund happens off-protocol and the protocol only orchestrates a three-step handshake via new party-only endpoints POST /api/orders/:id/cancel-refund/{request,decline,mark-refunded,withdraw,confirm} + GET /api/orders/:id/cancel-refund (party-gated state + caller\'s available actions): buyer requests (reason, ≤3 requests/order) → seller either declines (fulfilment continues) or marks refunded (optional refund reference) → buyer confirms the refund arrived (RISK: live-Passkey gate token, purpose=direct_pay_order_action, action=cancel_refund_confirm) → the protocol executes accepted→cancelled atomically (sys actor, db.transaction: request row CAS + transition + stock restore). NEUTRAL outcome: zero funds moved, no fee (fee AR accrues only at completed), no reputation/fault for either side. Buyer withdraw is allowed only BEFORE the seller marks refunded (afterwards the buyer must confirm or open a dispute — otherwise a refunded seller could be left with fulfilment still owed). The handshake does NOT block shipping: if the seller ships while a request is open the handshake goes stale fail-closed (mark-refunded/confirm reject with ORDER_NOT_ACCEPTED). Seller silence past the respond deadline (direct_pay.cancel_refund_respond_days, default 5) lazily expires the request — no auto-cancel (that would presume the refund happened); the buyer may re-request or escalate via the existing accepted→disputed evidence path. Escrow orders are rejected (NOT_DIRECT_PAY) — escrow refunds keep their own semantics; the new edge is system-only so no party can drive accepted→cancelled directly on ANY rail.', migration: 'Agents/integrators: a direct_p2p order in accepted can now reach \'cancelled\' via the bilateral cancel-refund handshake. Poll GET /api/orders/:id/cancel-refund for the open request + can_{request,respond,confirm,withdraw} flags. The confirm step requires a purpose=direct_pay_order_action WebAuthn gate token with purpose_data {order_id, action:\'cancel_refund_confirm\'} — agents cannot perform it (Passkey hard requirement). No existing state/edge/actor changed; escrow orders and all non-handshake paths are unaffected.' },
  { contract_version: 13, date: '2026-07-04', surface: 'entity', kind: 'added', summary: 'Direct Pay Rail 1: the per-order direct_pay_account_snapshot metadata gains OPTIONAL payable_* fields frozen at order create — payable_usdc (the order total in the platform display unit) and, when the chosen receive account is denominated in a supported non-USD fiat, payable_approx / payable_currency / payable_rate / payable_asof / payable_stale (a DISPLAY-ONLY reference conversion from the cached FX snapshot). Purpose: the buyer pay UI, the mark_paid timeline note (which now records 付款参考 + 应付 amount) and the seller reconciliation all reference ONE stable figure instead of re-converting with a drifting live rate. This is explicitly NOT a settlement quote: the rate may be stale (flagged), the authoritative amount is whatever the seller payment instruction states, and conversion failure simply omits payable_approx (order creation is never blocked). Additive — orders created before this revision lack the fields and clients fall back to live conversion / USDC-only display. Like v8, this snapshot is NOT part of the §②/§① fingerprint, so registered here by hand.', migration: 'Integrators reading direct_pay_account_snapshot may use payable_* when present; treat payable_approx as an at-create reference hint (payable_stale marks a cached/fallback rate), never as a settlement amount. Orders without the fields: convert client-side or show the USDC figure.' },
  { contract_version: 14, date: '2026-07-04', surface: 'capability', kind: 'changed', summary: 'Direct Pay Rail 1 disclosure acks (POST /api/direct-pay/disclosure-acks): (a) the endpoint now ALSO accepts stage:"both" — a single live-Passkey ceremony (gate token purpose_data.stage="both") records BOTH pre_select + pre_confirm ack rows at once, cutting the buyer\'s first-order Passkey ceremonies from 3 to 2 (the two disclosure SCREENS are still shown and confirmed; only the human-presence proof is consolidated; the two append-only ack rows and requireBothDisclosuresAcked evidence model are unchanged; the separate mark_paid RISK Passkey is unchanged). Existing single-stage POSTs (stage:"pre_select"|"pre_confirm") keep working. (b) The D1/D2 disclosure TEXT was reworded for accuracy ("non-guaranteed / no refund CAPABILITY / seller reputation penalty only" instead of "no refund") and its notice_version bumped d1.v1→d1.v2, d2.v1→d2.v2 — so GET /api/direct-pay/disclosure-acks/:orderId now returns the new text/versions and, for orders acked under v1, acked:{pre_select|pre_confirm}=false until re-acked under v2. recordDisclosureAck changed from INSERT-OR-IGNORE to an upsert so a re-ack under a new version actually refreshes the row (prior behavior would have silently no-op\'d and permanently blocked such orders). Not part of the §②/§① fingerprint (disclosure payload/versioning), registered here by hand.', migration: 'Buyers/integrators: the disclosure-ack POST may send stage:"both" with a purpose_data.stage="both" gate token to satisfy both disclosures in one ceremony; single-stage calls remain valid. After this revision, previously-recorded v1 acks read as un-acked (acked:false) until re-confirmed under d1.v2/d2.v2 — re-acking now works (upsert). No order state/edge/fund path changed; requireBothDisclosuresAcked still hard-gates mark_paid/confirm/confirm-in-person.' },
  { contract_version: 15, date: '2026-07-04', surface: 'capability', kind: 'added', summary: 'Direct Pay Rail 1 post-delivery RETURNS: direct_p2p orders can now use the standard return flow (POST /api/orders/:id/return-request on a completed order within return_days, seller decide, optional pickup logistics, negotiation messages) — the previous hard block (DIRECT_PAY_NO_REFUND) is REMOVED. Only the REFUND EXECUTION step differs from escrow: because the protocol never held the buyer\'s money, seller acceptance moves the return to a new await_refund status (off-protocol refund owed) instead of an escrow wallet transfer, then two new party-only endpoints complete the handshake — POST /api/return-requests/:id/mark-refunded (seller declares the off-protocol refund, optional refund_reference) → refund_marked, and POST /api/return-requests/:id/confirm-refund (buyer confirms the refund arrived; RISK: live-Passkey gate token purpose=direct_pay_order_action, purpose_data {order_id, action:"return_refund_confirm"}) → refunded (terminal). ZERO funds moved, ZERO automatic stock restore (post-outbound goods require offline inspection before manual restock — deliberate anti-oversell rule), platform fee receivable NOT auto-reversed (admin adjustment path). Escalation: refund_marked → buyer may escalate to dispute anytime (declaration ≠ receipt); await_refund → escalatable after direct_pay.return_refund_respond_days (default 5); the existing rejected / pending≥7d escalations still apply. Order status is NOT changed by a return (same as escrow returns). Full-amount confirmed returns decrement the product\'s best-effort completion_count (authoritative genuine-sale predicate already excludes direct_p2p). Escrow returns are COMPLETELY unchanged. return_requests rows gain refund_reference + await_refund_since columns and the two new statuses await_refund | refund_marked. Not part of the §②/§① fingerprint (no order state/edge/scope change), registered here by hand.', migration: 'Agents/integrators: a completed direct_p2p order now accepts return requests like escrow orders; DIRECT_PAY_NO_REFUND is no longer returned. Track the two new return_request statuses await_refund and refund_marked; the buyer confirm step requires a purpose=direct_pay_order_action WebAuthn gate token with purpose_data {order_id, action:"return_refund_confirm"} — agents cannot perform it (Passkey hard requirement). Do NOT expect stock to be restored or any wallet movement on a direct_p2p return.' },
  { contract_version: 16, date: '2026-07-04', surface: 'entity', kind: 'added', summary: 'Manual order-acceptance mode (accept_mode): sellers may require MANUAL acceptance before the buyer pays — per-product products.accept_mode overriding a store-wide users.store_accept_mode (effective mode is SNAPSHOT onto the order at create; later setting changes never affect in-flight orders; unset = auto = prior behavior on both rails). §① order lifecycle gains state pending_accept (manual direct_p2p orders land here at create instead of direct_pay_window) + 3 edges: created→pending_accept (system, at create), pending_accept→direct_pay_window (seller accepts — ONLY now does the payment window clock start and the payment instruction/QR become readable; a STATUS gate in the shared redaction projector hides the payment target during pending_accept even if D1/D2 are already acked), pending_accept→cancelled (seller decline / buyer withdraw / system timeout after direct_pay.accept_window_hours, default 24h — a NO-FAULT cancel: nobody has paid, zero funds move, stock restored via the pre-ship restock whitelist, both parties notified). New party-only endpoints POST /api/orders/:id/pending-accept/{accept,decline,cancel} + seller setting POST /api/seller/accept-mode. ESCROW rail deliberately does NOT use pending_accept: escrow is already a conditional intermediate state (funds locked at order, seller must accept within 24h or the buyer is auto-refunded in full) — accept_mode=auto on escrow simply auto-accepts at paid (formalizing the auto_accept Skill), manual/unset keeps todays flow. pending_accept counts toward the per-buyer open-order cap and the sellers in-flight fee estimate (griefing guards). Rationale: a non-custodial rail has no authorization-hold primitive — sequencing (accept before pay) is the only honest payment risk control.', migration: 'Agents placing direct_p2p orders: the create response may now return status pending_accept — do NOT expect payment instructions until the order reaches direct_pay_window (the payment-target fields stay redacted and the QR endpoint 404s during pending_accept). Track the new state + 3 edges from the lifecycle contract. Escrow orders and all orders on sellers/products without accept_mode=manual behave exactly as before.' },
  { contract_version: 17, date: '2026-07-04', surface: 'capability', kind: 'added', summary: 'Region-based shipping-fee templates: sellers may predefine per-region shipping fees + estimated delivery time — per-product products.shipping_template overriding a store-wide users.store_shipping_template (JSON entries {region (uppercase code or "*" wildcard = rest of world), fee (same unit as the product price), est_days (display-only)}). When an EFFECTIVE template exists for a product, POST /api/orders REQUIRES a new body field ship_to_region (else 400 SHIP_REGION_REQUIRED); a covered region adds the template fee into total_amount BEFORE any money/gate logic on BOTH rails (escrow lock, dp per-tx cap and platform fee all see the fee-inclusive total — same convention as the insurance premium; no separate shipping settlement subject in v1) and snapshots orders.{ship_to_region, shipping_fee, shipping_est_days} (later template edits never affect in-flight orders); an uncovered region REJECTS order creation with 409 SHIP_REGION_NOT_COVERED (a quote-on-accept handshake for uncovered regions ships in a later revision). Products/sellers WITHOUT a template behave exactly as before (ship_to_region optional, no fee). New endpoints: POST /api/seller/shipping-template (seller: store default and/or per-product override; null/[] clears) and public GET /api/products/:id/shipping-options (effective template + region_required flag — buyers can see coverage/fee/ETA before ordering). est_days is display-only and does NOT feed the fulfilment-deadline clocks. Payment timing is UNCHANGED on both rails. Not part of the §②/§① fingerprint (create-body field + non-fingerprinted endpoints), registered by hand.', migration: 'Agents placing orders: call GET /api/products/:id/shipping-options first — if region_required, include ship_to_region (uppercase region code) in POST /api/orders and expect the returned total to include the template shipping fee; handle 400 SHIP_REGION_REQUIRED and 409 SHIP_REGION_NOT_COVERED. Orders on products without a template are unaffected.' },
  { contract_version: 18, date: '2026-07-04', surface: 'capability', kind: 'added', summary: 'Shipping quote-on-accept handshake (direct_p2p only): when a product has an effective shipping template, the buyer region is NOT covered, and the seller has opted in (products.shipping_quote_ok ?? users.store_shipping_quote_ok, default OFF — settable via POST /api/seller/shipping-template {store_quote_ok | product_id+quote_ok}; surfaced as quote_outside_template on GET /api/products/:id/shipping-options), POST /api/orders no longer 409s: the order is created into pending_accept with shipping_quote_required=1 (REGARDLESS of accept_mode) and ZERO shipping fee in the total. Flow: seller POST /api/orders/:id/pending-accept/quote {shipping_fee, est_days?, note?} — the quote may only ADD a shipping-fee line (goods price untouchable) and goods+fee must fit the per-tx cap SNAPSHOT frozen at create (409 QUOTE_EXCEEDS_CAP — shipping cannot smuggle past the small-amount rail boundary); re-quoting before confirmation is allowed and each quote resets the response window (direct_pay.quote_confirm_hours, default 48h, same pending_accept_deadline → the expiry sweep covers both quote silence and confirm silence). Buyer POST .../confirm-quote → atomically (one db.transaction) total_amount += fee (integer base-units math), shipping_fee/est_days snapshotted, payable_* reference conversion REBUILT at the new total, payment window clock starts, order → direct_pay_window. Buyer decline = existing /cancel; seller withdraw = existing /decline (both no-fault + restock, nobody has paid). Plain /accept on a quote order is rejected (409 QUOTE_REQUIRED) so the fee step cannot be bypassed. AML monitor re-runs after the total change (fail-soft). Escrow-rail quote remains unavailable (create still 409 SHIP_REGION_NOT_COVERED; requires the pay-after-accept money path — separate revision). No new order state or edge (rides pending_accept + the existing pending_accept→direct_pay_window system edge); registered by hand.', migration: 'Agents on direct_p2p: create may return status pending_accept with shipping_quote_required=true even for auto-accept products — wait for the seller quote, then read shipping_quote_fee and call confirm-quote to consent to the NEW total (total_amount changes on confirmation; the D1/D2 + mark_paid gates are unchanged and payment info stays hidden until direct_pay_window). Do not expect /accept to work on quote orders (409 QUOTE_REQUIRED).' },
]

export function buildChangeFeed() {
  return {
    current_contract_version: CONTRACT_VERSION,
    fingerprints: contractFingerprints(),
    deprecation_policy: 'Sunset-bound surfaces carry RFC 8594 Deprecation + Sunset headers; window ≥ 1 contract_version. Any integrator-observable contract change bumps contract_version and appends a change entry (kind: added|changed|deprecated|removed). A fingerprint CI guard makes a silent change un-mergeable.',
    deprecations: [] as Array<{ surface: string; sunset: string; replacement?: string }>,
    changes: CONTRACT_CHANGES,
    note: 'Poll with your last-seen contract_version and apply entries with a higher contract_version. The fingerprints let you detect drift without diffing the whole contract: if combined != your cached value, re-read /.well-known/webaz-{capabilities,entities}.json.',
  }
}
