#!/usr/bin/env tsx
/**
 * Seed the public `webaz_contribute` task board with the OPEN-SOURCE-FIRST-TASKS (16).
 *
 * Operator/admin tool — run ONCE at launch (Genesis Step 9), AFTER:
 *   (a) the public repo exists + is public, and
 *   (b) RFC-019 is public (T16's authority).
 *
 * Default = DRY-RUN: it runs the full insert inside a transaction that is ROLLED BACK, so the store's
 * validation (insertBuildTaskAgentMetadata throws on any contract violation) is exercised against the real
 * DB without persisting. Pass --commit to persist.
 *
 * This data MIRRORS docs/OPEN-SOURCE-FIRST-TASKS.md (the human spec) — keep them in sync. The script is the
 * machine-readable source the board is seeded from.
 *
 * Admin seed DIRECT-INSERTS the build_tasks row (with audience='public' metadata) — it legitimately runs
 * above the per-user CREATE_RATE_PER_DAY anti-spam guard in createBuildTask (16 > 10/day). It is otherwise
 * identical to the engine's insert (id, title, area, description, rfc_ref, status='open', created_by) +
 * logTaskEvent('created') + insertBuildTaskAgentMetadata.
 *
 * Usage:
 *   tsx scripts/seed-open-source-tasks.ts --creator <usr_id> [--db <path>]            # dry-run (validate)
 *   tsx scripts/seed-open-source-tasks.ts --creator <usr_id> --db <path> --commit     # persist
 *   (db also via WEBAZ_DB_PATH; prod: /root/.webaz/webaz.db via `railway ssh`, mirror operator-ingest runbook)
 *
 * NON-GOALS: no governance scoring / rewards / tokenomics / ranking. value_state is always 'uncommitted'.
 */
import { existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import Database from 'better-sqlite3'
import { generateId } from '../src/layer0-foundation/L0-1-database/schema.js'
import { initBuildTasksSchema, logTaskEvent } from '../src/layer2-business/L2-9-contribution/build-tasks-engine.js'
import {
  initBuildTaskAgentMetadataSchema,
  insertBuildTaskAgentMetadata,
  type BuildTaskAgentMetadata,
} from '../src/layer2-business/L2-9-contribution/build-task-agent-metadata-store.js'
import { CONTRIBUTION_TYPES } from '../src/layer2-business/L2-9-contribution/github-credential/github-credential.schema.js'

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

// ── shared boundary (mirrors §A of OPEN-SOURCE-FIRST-TASKS.md) ──
const GLOBAL_PROHIBITED = [
  'Do not touch wallet / payment / escrow / settlement core',
  'Do not touch the auth/permission core, the iron rules (requireHumanPresence), WebAuthn/Passkey, or KYC',
  'Do not run DB migrations or alter the order state machine',
  'Do not touch the content_hash trust-root core logic, the content-admission allowlist, or incentive / anti-sybil accounting',
  'Do not flip the matching_rewards activation switch',
  'PRs MUST target the canonical WebAZ repo; done != merge — a human maintainer reviews and merges',
  'Never submit a prior/current employer\'s code, internal designs, or confidential info (personal-time contributions only)',
]
const DOD = 'All acceptance_criteria met; DCO sign-off present; PR targets the canonical WebAZ repo. done != merge — a human maintainer reviews and merges.'

type Seed = {
  ref: string                 // T1..T16 (used for idempotency note + dependency wiring)
  title: string
  area: string
  description: string         // = the doc's summary
  meta: BuildTaskAgentMetadata
}

// risk → autonomy/claimability (high/critical gated by the store CHECKs)
const lowAuto = { agent_autonomy: 'autonomous' as const, auto_claimable: true }
const medSup = { agent_autonomy: 'supervised' as const, auto_claimable: true }

const base = (m: Partial<BuildTaskAgentMetadata>): BuildTaskAgentMetadata => ({
  task_type: 'docs',
  allowed_paths: [],
  forbidden_paths: [],
  prohibited_actions: GLOBAL_PROHIBITED,
  risk_level: 'low',
  audience: 'public',
  agent_autonomy: 'autonomous',
  auto_claimable: true,
  human_confirmation_points: [],
  required_capabilities: [],
  acceptance_criteria: [],
  verification_commands: [],
  expected_results: '',
  deliverables: [],
  definition_of_done: DOD,
  estimated_duration_min_minutes: 30,
  estimated_duration_max_minutes: 60,
  estimated_context_size: 'small',
  estimated_agent_budget: 'small',
  dependencies: [],
  blocking_conditions: [],
  value_state: 'uncommitted',
  contribution_type: 'maintenance',   // RFC-017 §5 canonical default; docs/i18n map here (no docs-specific §5 bucket)
  accountable_party_required: true,
  ...m,
} as BuildTaskAgentMetadata)

const B = { estimated_duration_min_minutes: 120, estimated_duration_max_minutes: 240, estimated_context_size: 'medium' as const, estimated_agent_budget: 'moderate' as const }

const TASKS: Seed[] = [
  // ── §C Group A — 5 × 30–60 min (low) ──
  { ref: 'T1', title: 'Document the public protocol manifest (/.well-known/webaz-protocol.json)', area: 'docs',
    description: 'Field-by-field documentation of the public protocol manifest (generated by L0-5-manifest/manifest.ts): meaning of each key, trust anchors, how an integrator/agent reads it.',
    meta: base({ task_type: 'docs', ...lowAuto, source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#T1',
      allowed_paths: ['docs/manifest-reference.md'], forbidden_paths: ['any code', 'the manifest generator'],
      required_capabilities: ['markdown', 'read-source'],
      acceptance_criteria: ['every current manifest field documented + accurate vs generator output', 'trust-anchor fields flagged', 'no field invented that the generator does not emit'],
      verification_commands: ['fetch /.well-known/webaz-protocol.json (local) and diff the field list against the doc'],
      expected_results: 'one markdown reference doc (docs/manifest-reference.md)', deliverables: ['docs/manifest-reference.md'] }) },
  { ref: 'T2', title: 'i18n: complete one missing language on the public discover page', area: 'i18n',
    description: 'Add a missing-language (en/ja/ko — pick one) translation for the public #discover UI strings, against existing zh/en keys in i18n.js.',
    meta: base({ task_type: 'i18n', ...lowAuto, contribution_type: 'maintenance', source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#T2',
      allowed_paths: ['src/pwa/public/i18n.js (translations only)'], forbidden_paths: ['any logic', 'any string implying earnings/recruiting'],
      required_capabilities: ['i18n', 'translation'],
      acceptance_criteria: ['target-language keys map 1:1 to zh with no gaps', 'no recruiting / income-promise wording introduced', 'npm run check:pwa-syntax green'],
      verification_commands: ['npm run check:pwa-syntax'], expected_results: 'the completed i18n entries', deliverables: ['i18n.js translation entries'] }) },
  { ref: 'T3', title: 'Agent usage example for one read-only MCP tool', area: 'docs',
    description: 'Pick a read-only MCP tool (webaz_search / webaz_get_status / webaz_leaderboard); document how an agent calls it, typical input/output, one common misuse — grounded in the tool schema.',
    meta: base({ task_type: 'docs', ...lowAuto, source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#T3',
      allowed_paths: ['docs/mcp-examples/*.md'], forbidden_paths: ['any code', 'anything about bypassing money/auth tools'],
      required_capabilities: ['markdown', 'mcp-tools'],
      acceptance_criteria: ['example reproducible + matches the tool schema', 'states the tool auth requirement', 'calls out 1 real misuse'],
      verification_commands: ['human cross-check example vs tool schema'], expected_results: 'one markdown doc under docs/mcp-examples/', deliverables: ['docs/mcp-examples/<tool>.md'] }) },
  { ref: 'T4', title: 'README structure guide + badges', area: 'docs',
    description: 'Top-level directory guide (one line of responsibility per top dir) + CI/license badges to lower onboarding cost.',
    meta: base({ task_type: 'docs', ...lowAuto, source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#T4',
      allowed_paths: ['README.md', 'docs/STRUCTURE.md'], forbidden_paths: ['any code', 'internal-only strategy doc contents'],
      required_capabilities: ['markdown'],
      acceptance_criteria: ['directory guide matches the real tree', 'badge links valid', 'references no internal-only doc'],
      verification_commands: ['human cross-check the dir list vs the repo'], expected_results: 'updated README + docs/STRUCTURE.md', deliverables: ['README.md update', 'docs/STRUCTURE.md'] }) },
  { ref: 'T5', title: 'Typed-error-code reference doc', area: 'docs',
    description: 'Pick one group of existing typed outcomes (e.g. the GitHub fetch-adapter codes) and document per code what it means + how an agent handles it. Existing codes only, no code change.',
    meta: base({ task_type: 'docs', ...lowAuto, source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#T5',
      allowed_paths: ['docs/error-codes.md'], forbidden_paths: ['any error-logic code', 'adding/changing any code value'],
      required_capabilities: ['markdown', 'read-source'],
      acceptance_criteria: ['covers all existing codes in that group', 'each meaning matches the actual trigger condition in source', 'handling advice is sound'],
      verification_commands: ['human cross-check doc code list vs the source outcome enum'], expected_results: 'one error-codes doc', deliverables: ['docs/error-codes.md'] }) },

  // ── §D Group B — 5 × 2–4 h ──
  { ref: 'T6', title: 'content_hash verification SDK (one language)', area: 'sdk',
    description: 'Reusable library exporting canonicalize() + verifyContentHash(endpoint, expectedHash) for agents to verify p2p content. Implements §B (canonical-JSON) exactly.',
    meta: base({ ...B, task_type: 'sdk_example', ...lowAuto, contribution_type: 'code', source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#B', dependencies: ['§B canonical-JSON spec'],
      allowed_paths: ['sdk/p2p-verify/'], forbidden_paths: ['the content_hash generation/admission core in src/ (reuse the rule only to verify)'],
      required_capabilities: ['typescript', 'crypto-sha256'],
      acceptance_criteria: ['canonicalize() byte-identical to order-chain.ts canonicalSerialize on the §B fixture set (no-drift test)', 'tamper any field => verify fails; key reorder => hash unchanged; arrays keep order; null kept; non-ASCII per §B.4', 'follows §B points 1–6 precisely'],
      verification_commands: ['npm test (SDK) green incl. the no-drift diff vs the src serializer'], expected_results: 'SDK package with tests + README citing §B', deliverables: ['sdk/p2p-verify/ package', 'tests', 'README'] }) },
  { ref: 'T7', title: 'seller-export -> list_product field-mapping skill (one platform)', area: 'sdk',
    description: 'Script: input a seller\'s own export (Taobao/Shopify) CSV/JSON; parse + map to webaz_list_product fields; output a publish-ready structure.',
    meta: base({ ...B, task_type: 'sdk_example', ...medSup, risk_level: 'medium', contribution_type: 'code', source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#T7', dependencies: ['T15 (mapping standard) helpful, not blocking'],
      allowed_paths: ['examples/catalog-import-<platform>/'], forbidden_paths: ['any scraping of external platforms (accept seller-exported files only)', 'payment/inventory core'],
      prohibited_actions: [...GLOBAL_PROHIBITED, 'Do NOT scrape external platforms — only process the seller\'s own exported files'],
      required_capabilities: ['nodejs', 'data-mapping'],
      acceptance_criteria: ['sample export => correct mapping to list_product fields', 'missing fields => null/default, NEVER invented (never-guess)', 'explicit error on export-format mismatch (no silent swallow)', 'doc states "only the seller\'s own exported data, not scraping"'],
      verification_commands: ['node examples/catalog-import-<platform>/test.js (bundled sample export)'], expected_results: 'parse skill + sample file + mapping doc', deliverables: ['examples/catalog-import-<platform>/', 'sample export', 'mapping doc'] }) },
  { ref: 'T8', title: 'seller p2p endpoint reference implementation', area: 'sdk',
    description: 'Minimal seller p2p endpoint: static service returning product-detail JSON by product_id + a helper computing content_hash (§B) + content_signature HMAC-SHA256(api_key, content_hash|content_signed_at).',
    meta: base({ ...B, task_type: 'sdk_example', ...medSup, risk_level: 'medium', contribution_type: 'code', source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#T8', dependencies: ['§B', 'pairs with T6'],
      allowed_paths: ['examples/seller-p2p-node/'], forbidden_paths: ['src/ core', 'WebAZ-side anchoring/admission (seller-side reference only)'],
      required_capabilities: ['nodejs', 'http', 'crypto-hmac'],
      acceptance_criteria: ['GET /<product_id> returns valid JSON', 'helper content_hash (§B canonical) verifies via T6 and the protocol signature check', 'signature rule matches webaz_p2p_product exactly: HMAC-SHA256(api_key, content_hash + "|" + content_signed_at)', 'README: local start -> cloud migration; cites §B as canonical-hash source of truth'],
      verification_commands: ['start service + verify a fetched product via the T6 SDK'], expected_results: 'reference impl + hash/sign helper + README', deliverables: ['examples/seller-p2p-node/', 'hash/sign helper', 'README'] }) },
  { ref: 'T9', title: 'anti-oversell config end-to-end example (existing fields)', area: 'sdk',
    description: 'Example + doc using list_product existing auto_delist_on_zero / low_stock_threshold to prevent oversell: publish -> simulate stock->0 -> auto-delist -> document the trigger. Existing fields only.',
    meta: base({ ...B, task_type: 'sdk_example', ...medSup, risk_level: 'medium', contribution_type: 'code', source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#T9',
      allowed_paths: ['examples/inventory-guard/', 'docs/inventory-guard.md'], forbidden_paths: ['inventory-decrement / order core', 'list_product backend'],
      required_capabilities: ['nodejs', 'mcp-tools'],
      acceptance_criteria: ['example walks "stock->0 => auto-delist"', 'doc accurately describes auto_delist_on_zero / low_stock_threshold (existing list_product fields)'],
      verification_commands: ['run the example, observe auto-delist firing'], expected_results: 'example script + doc', deliverables: ['examples/inventory-guard/', 'docs/inventory-guard.md'] }) },
  { ref: 'T10', title: 'seller NL-instruction prototype (read + publish only; never funds)', area: 'sdk',
    description: 'Small agent instruction-layer prototype mapping seller natural language to the right MCP tool calls (list_product / get_status). Read + publish/(de)list only; never funds/withdraw/escrow.',
    meta: base({ ...B, task_type: 'sdk_example', ...medSup, risk_level: 'medium', contribution_type: 'code', source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#T10', dependencies: ['T3 helpful'],
      allowed_paths: ['examples/seller-agent-cli/'], forbidden_paths: ['any wallet/withdraw/escrow/payment mapping', 'iron-rule actions'],
      prohibited_actions: [...GLOBAL_PROHIBITED, 'A funds-type instruction must be refused with "needs PWA + Passkey" — NEVER proxied'],
      required_capabilities: ['nodejs', 'agent-instruction-design'],
      acceptance_criteria: ['3–5 example instructions map correctly', 'a funds-type instruction => explicit refusal + "needs PWA + Passkey", never proxied', 'never invents capabilities a tool does not have'],
      verification_commands: ['run examples; verify mapping + that funds instructions are refused'], expected_results: 'CLI prototype + mapping table + README', deliverables: ['examples/seller-agent-cli/', 'mapping table', 'README'] }) },

  // ── §E Group C — 3 tests/audit ──
  { ref: 'T11', title: 'p2p verification adversarial test suite', area: 'tests',
    description: 'Adversarial fixtures for the §B verification flow: normal, single-field tamper, key reorder, null values, non-ASCII, oversized payload, invalid JSON, hash mismatch.',
    meta: base({ ...B, task_type: 'tests', ...medSup, risk_level: 'medium', contribution_type: 'tests', source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#T11', dependencies: ['T6 (or T1)', '§B'],
      allowed_paths: ['scripts/__tests__/', 'sdk/p2p-verify/__tests__/'], forbidden_paths: ['the verification/generation core under test (add tests only)'],
      required_capabilities: ['testing', 'typescript'],
      acceptance_criteria: ['>= 8 fixtures covering normal + multiple attacks/anomalies incl. §B edge cases (recursive sort, array order, null kept, non-ASCII, undefined-key rejected)', 'each fixture has an explicit expected result + a comment on what it tests', 'includes a no-drift check against order-chain.ts canonicalSerialize', 'all green'],
      verification_commands: ['npm test green'], expected_results: 'test suite + fixture set', deliverables: ['test suite', 'fixture set'] }) },
  { ref: 'T12', title: 'read-only public-API smoke test set', area: 'tests',
    description: 'Smoke tests for read-only public endpoints (search / get_status / leaderboard / info): response shape, typed error on bad input, sensitive fields stay hidden (GMV/amounts hidden by design). Read-only.',
    meta: base({ ...B, task_type: 'tests', ...medSup, risk_level: 'medium', contribution_type: 'tests', source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#T12',
      allowed_paths: ['scripts/smoke/'], forbidden_paths: ['any write/order/payment endpoint', 'no auth-bypass probing'],
      required_capabilities: ['testing', 'http-api'],
      acceptance_criteria: ['covers the listed read-only endpoints', 'asserts leaderboard etc. DO hide GMV/amounts (privacy design)', 'bad input => typed error (not a crash)'],
      verification_commands: ['node scripts/smoke/run.js (against local/testnet)'], expected_results: 'smoke test set + run notes', deliverables: ['scripts/smoke/', 'run notes'] }) },
  { ref: 'T13', title: 'i18n completeness audit script', area: 'audit',
    description: 'CI-friendly script scanning i18n.js: report keys with zh but no EN (and other lang gaps), output a gap list, non-zero exit on gaps. Key-position-aware matching, not raw substring.',
    meta: base({ task_type: 'audit', ...lowAuto, risk_level: 'low', contribution_type: 'audit', estimated_duration_min_minutes: 60, estimated_duration_max_minutes: 120, source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#T13',
      allowed_paths: ['scripts/i18n-audit.ts', 'scripts/i18n-audit.js'], forbidden_paths: ['do not change i18n content (audit only)'],
      required_capabilities: ['nodejs', 'scripting'],
      acceptance_criteria: ['correctly reports missing keys', 'key-position-aware matching (\'key\': with the colon), NOT raw substring (avoid the dogfood-round-3 false-negative)', 'exit code: gaps => non-zero (CI gate); readable gap list'],
      verification_commands: ['node scripts/i18n-audit.js'], expected_results: 'audit script + usage doc', deliverables: ['scripts/i18n-audit.{ts,js}', 'usage doc'] }) },

  // ── §F Group D — 2 small RFC ──
  { ref: 'T14', title: 'RFC: node discovery / content_hash -> replica index', area: 'governance',
    description: 'Small RFC designing how WebAZ maintains a content_hash -> list-of-replica-nodes index (design only): what it stores (pointers/metadata, not bytes), node up/down, agent query, composition with §B verification.',
    meta: base({ ...B, task_type: 'governance', ...medSup, risk_level: 'medium', contribution_type: 'governance', source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#T14',
      allowed_paths: ['docs/rfcs/RFC-node-discovery.md'], forbidden_paths: ['no code', 'no incentive-accounting design (core, maintainer-owned)'],
      required_capabilities: ['technical-writing', 'protocol-design'],
      acceptance_criteria: ['explicit "pointers/metadata only, not content bytes"', 'fallback when nodes are unstable (origin fallback + multi-replica)', 'does not stray into incentive/anti-sybil design', 'flags open questions for maintainer decision'],
      verification_commands: ['maintainer review'], expected_results: 'one RFC', deliverables: ['docs/rfcs/RFC-node-discovery.md'] }) },
  { ref: 'T15', title: 'RFC: seller-export -> WebAZ field-mapping standard', area: 'governance',
    description: 'RFC defining the standard mapping external-platform seller export -> webaz_list_product fields: field-correspondence table, never-guess missing fields, normalization, compliance boundary (own export only).',
    meta: base({ ...B, task_type: 'governance', ...lowAuto, risk_level: 'low', contribution_type: 'governance', estimated_agent_budget: 'small', source_ref: 'docs/OPEN-SOURCE-FIRST-TASKS.md#T15',
      allowed_paths: ['docs/rfcs/RFC-catalog-import-mapping.md'], forbidden_paths: ['no impl', 'no scraping design'],
      prohibited_actions: [...GLOBAL_PROHIBITED, 'Do NOT design scraping — seller\'s own export only'],
      required_capabilities: ['technical-writing', 'data-mapping'],
      acceptance_criteria: ['at least one platform\'s complete field-mapping table', 'explicit never-guess (missing => null/default, never invented)', 'explicit compliance boundary: seller\'s own export only, not scraping', 'flags open questions'],
      verification_commands: ['maintainer review'], expected_results: 'one RFC', deliverables: ['docs/rfcs/RFC-catalog-import-mapping.md'] }) },

  // ── §I Flagship feature (1 · high-risk · maintainer-led · the §A exception) ──
  { ref: 'T16', title: 'GitHub OAuth identity linking (per RFC-019)', area: 'identity',
    description: 'Implement a low-friction "Connect GitHub" OAuth identity-linking path that preserves the security model (Passkey still gates the bind; ownership server-verified; Gist fallback retained). Per RFC-019, milestones M2–M7.',
    meta: base({ task_type: 'code', risk_level: 'high', agent_autonomy: 'human_in_the_loop', auto_claimable: false,
      contribution_type: 'code', estimated_duration_min_minutes: 480, estimated_duration_max_minutes: 2400,
      estimated_context_size: 'large', estimated_agent_budget: 'large', source_ref: 'docs/rfcs/RFC-019-github-oauth-identity-linking.md', dependencies: ['RFC-019 (M1)'],
      allowed_paths: ['src/layer2-business/L2-9-contribution/github-oauth-adapter.ts (new)', 'oauth_link_states schema + store (new)', 'oauth/* endpoints in src/pwa/routes/contribution-identity.ts', 'PWA "Connect GitHub" UI + i18n', 'docs/runbooks/github-oauth-setup.md', 'proof_method=github_oauth extension to the claim engine (M4, maintainer review required)'],
      forbidden_paths: ['must NOT weaken or bypass requireHumanPresence / the human-presence gate', 'WebAuthn/Passkey core', 'the existing gist proof verifier trust root', 'the identity_bindings_active double-bind PK', 'any money/escrow/auth-permission core'],
      prohibited_actions: [...GLOBAL_PROHIBITED, 'Token must NEVER be persisted or logged; OAuth scope = read:user only (no repo/write)', 'OAuth success alone must NEVER bind — the Passkey ceremony gates the commit'],
      human_confirmation_points: ['RFC-019 accepted by maintainer before M2', 'maintainer security review confirming Passkey gating + ownership verification are unchanged before M4/M5 merge'],
      required_capabilities: ['typescript', 'oauth', 'security', 'webauthn-awareness'],
      acceptance_criteria: ['bind commits ONLY behind the Passkey ceremony — OAuth success alone never binds', 'GitHub ownership proven by server-side GET /user (numeric id), never client-asserted', 'Gist fallback intact; existing bindings unaffected; both paths produce identical bindings', 'PKCE + single-use session-bound state (CSRF); access token used once then discarded; fail-closed (503) when OAuth creds unset', 'double-bind still blocked; rebind = revoke event + fresh proof + Passkey (append-only)'],
      verification_commands: ['new schema/adapter/engine/route tests green AND the existing identity-claim suite still green', 'npm run build', 'npm run check:api-docs-fresh'],
      expected_results: 'RFC-019 milestones M2–M7 as separate, independently-green PRs', deliverables: ['oauth_link_states schema + store', 'github-oauth-adapter', 'oauth/* routes (Passkey-gated)', 'PWA Connect-GitHub UI', 'docs/runbook'] }) },
]

function parseArgs(argv: string[]) {
  const get = (k: string) => { const i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : undefined }
  return { creator: get('--creator') || process.env.SEED_CREATOR_ACCOUNT_ID,
    db: get('--db') || process.env.WEBAZ_DB_PATH, commit: argv.includes('--commit') }
}

// Fail-closed preflight (pure, no DB). Runs BEFORE any DB open / write, in BOTH dry-run and --commit:
//   1. every contribution_type is a canonical RFC-017 §5 type (the store does NOT CHECK this column, so an
//      off-taxonomy value would otherwise persist silently and later misclassify in metering/ingestion);
//   2. every local docs source_ref a task cites as its AUTHORITY already exists in the tree — this blocks
//      seeding a task whose spec/RFC has not landed yet (e.g. a future T-task before its RFC is public).
//   deliverables/output paths are intentionally NOT checked — those are what the task is meant to produce.
function preflightSeeds(): void {
  const valid = new Set<string>(CONTRIBUTION_TYPES)
  const errors: string[] = []
  for (const t of TASKS) {
    if (!valid.has(t.meta.contribution_type)) {
      errors.push(`${t.ref}: contribution_type '${t.meta.contribution_type}' is not an RFC-017 §5 type {${[...valid].join(', ')}}`)
    }
    const ref = t.meta.source_ref
    if (ref && ref.startsWith('docs/')) {
      const filePath = ref.split('#')[0]   // strip #anchor
      if (!existsSync(path.join(REPO_ROOT, filePath))) {
        errors.push(`${t.ref}: source_ref authority doc absent in tree: ${filePath}`)
      }
    }
  }
  if (errors.length) {
    console.error(`FAIL preflight (no DB opened, nothing written):\n  - ${errors.join('\n  - ')}`)
    process.exit(2)
  }
}

function main(): void {
  preflightSeeds()
  const { creator, db: dbPath, commit } = parseArgs(process.argv.slice(2))
  if (!dbPath) { console.error('FAIL: --db <path> or WEBAZ_DB_PATH required'); process.exit(2) }
  if (!creator) { console.error('FAIL: --creator <usr_id> required (the operator/maintainer account that owns the seeded tasks)'); process.exit(2) }

  const db = new Database(dbPath)
  db.pragma('foreign_keys = ON')
  initBuildTasksSchema(db)
  initBuildTaskAgentMetadataSchema(db)

  const creatorExists = (db.prepare('SELECT COUNT(*) AS n FROM users WHERE id = ?').get(creator) as { n: number }).n > 0
  if (!creatorExists) { console.error(`FAIL: creator account ${creator} not found in users`); process.exit(2) }

  const existsByTitle = db.prepare('SELECT id FROM build_tasks WHERE title = ? AND created_by = ?')
  const insertTask = db.prepare(`INSERT INTO build_tasks (id, title, area, description, rfc_ref, status, created_by) VALUES (?,?,?,?,?, 'open', ?)`)

  let created = 0, skipped = 0
  const seedAll = () => {
    for (const t of TASKS) {
      const dup = existsByTitle.get(t.title, creator) as { id: string } | undefined
      if (dup) { console.log(`  skip   ${t.ref}: already seeded (${dup.id})`); skipped++; continue }
      const id = generateId('bt')
      const rfcRef = t.meta.source_ref && t.meta.source_ref.includes('rfcs/') ? t.meta.source_ref : null
      insertTask.run(id, t.title, t.area, t.description, rfcRef, creator)
      logTaskEvent(db, id, creator, null, 'open', `seeded: ${t.ref} (open-source first tasks)`)
      insertBuildTaskAgentMetadata(db, id, t.meta)   // validates enums + invariants; throws on any violation
      console.log(`  create ${t.ref} [${t.meta.risk_level}/${t.meta.agent_autonomy}/${t.meta.audience}] -> ${id}: ${t.title}`)
      created++
    }
  }

  console.log(`Seeding ${TASKS.length} tasks | db=${dbPath} | creator=${creator} | mode=${commit ? 'COMMIT' : 'DRY-RUN (rollback)'}`)
  if (commit) {
    db.transaction(seedAll)()
  } else {
    // dry-run: run inside a transaction and roll back, so the store validation is exercised without persisting
    const SENTINEL = Symbol('rollback')
    try { db.transaction(() => { seedAll(); throw SENTINEL })() } catch (e) { if (e !== SENTINEL) throw e }
  }
  console.log(`\nDONE — created ${created}, skipped ${skipped}, total ${TASKS.length}. ${commit ? 'PERSISTED.' : 'DRY-RUN (nothing written).'}`)
  db.close()
}

main()
